### ISSUE TITLE
Feature Request: exercises

### ISSUE THREAD

**Issue by cnasc** [coinbase/build-onchain-apps#118]
### Describe the solution you'd like

We may be able to create some incomplete applications that can be used as exercises. For example, we have the scaffolding of the mint page, but the onchain interaction doesn't work yet and has failing unit tests. The goal is to complete the page, indicated by a passing test suite. This offers newcomers a chance to level up, and maybe we can mint a diploma NFT for them if they complete all the challenges.

**Comment by Zizzamia** [comment]
I love where your mind is, and I think we can start by having each App experience (Buy, Mint, etc..), have the top part the real demo, and the bottom part a guide. A step by step guide that shows the code used and how it connects with each other.

These guide can be ver beneficial in different factor
- SEO: it will make the all experience easier to find
- Dev Tips: you can jump between section and just read or care the one you are the most confused
- Video: can be the trascript of a video we can produce and have on the page as well
- Mantain: as we improve the code, than we can improve the guide and adapt it over time

The passing test suite, that can be the final step, where we force delete with the CLI just some code, and folks can follow the guide just mentioned to recreate them. And ofcourse test it works.

**Comment by Zizzamia** [comment]
Closing this one in favor of starting some Good First Issue.
