### ISSUE TITLE
Documentation Request: yarn dev script does not exist

### ISSUE THREAD

**Issue by giorgosn** [coinbase/build-onchain-apps#129]
### Is your documentation request related to a problem? Please describe.

In documentation seems that yarn dev command does run the project locally. But there is not this script

**Comment by Zizzamia** [comment]
Ciao @giorgosn, can you share step by step how you are using Build Onchain Apps. It can help me figure out what is missing.

**Comment by Zizzamia** [comment]
@giorgosn my guess is that you clone the repo and tried to run `yarn dev` from the root.

`yarn dev` is available when you create a new project by doing
```
npx @coinbase/build-onchain-apps@latest create
```
and than access the folder where you new project is and there you can run `yarn dev` after ofcourse you install the dependencies.

I hope this helps, and I am going to close the issue.

Feel free to ping us again if anything is not working.
