### ISSUE TITLE
Bug: top of mind issues to solve 

### ISSUE THREAD

**Issue by Zizzamia** [coinbase/build-onchain-apps#147]
A top of mind list

- [x]  for `app/build-onchain-apps` when running `yarn build` seems not working anymore, seems related with the recent babel changes. Also to prevent future build breaking we should add a `yarn build` check in CI
- [x] types seems not working for `wagmi`, `viem` and `abitype`. It says `Cannot find module 'abitype'. Did you mean to set the 'moduleResolution' option to 'node', or to add aliases to the 'paths' option?`. It's odd because I can see in the node_module files the `.d.ts` file being ship. **Done** #148
- [x] I was testing the minting experience and the network fee was like $19, which seems a bit too high. Let's deep dive on it and see what's going on there. Btw it was on Base Goerli.

**Comment by Zizzamia** [comment]
@Sneh1999 @wespickett @cnasc @renanmav @codynova, I am using this bug to keep track some of the issues I am discovering. Feel free to change the description and add more things.

Ideally this is a list we can use to pick up random bugs to solve on our own.

**Comment by Hi2885** [comment]
This will be a nice fix

**Comment by Zizzamia** [comment]
Closing this first round of issues.
