### ISSUE TITLE
Feature Request: top of mind ideas we want to build

### ISSUE THREAD

**Issue by Zizzamia** [coinbase/build-onchain-apps#150]
Here some top of mind ideas we want to build.

**Home page**
- [ ] Similar to what Radix or Viem site does, explain how to use Build Onchain Apps and the value from it
- [ ] ~~~

**Mint page**
- [ ] Show a link on where the minted NFT is, either on testnet or mainnet.
- [ ] After something is minted show a status/confirmation message.
- [ ] Have a documentation that shows the steps on how to mix the pre-build functionality:
        - how to use a Mint contract
        - how connect the contract with the UI
- [ ] ~~~~

**Pay page**
- [ ] Re-Design the buying coffee experience to make it more intuitive to use, right there is simple confusion on why do I need a name or a message. And explain if you send it, it will add the memo and name Onchain.
- [ ] Why do we need names? We should default to ENS!!! Or ask a Name if you don't have an ENS.
- [ ] Have the UI reflect all functionality of the Contract.
- [ ] ~~~~

**DeFi page**
- [ ] ~~~~
- [ ] ~~~~

**Collaborate page**
- [ ] ~~~~
- [ ] ~~~~

**Solidity**
- [x] In the main README, have a bit more clear the Out of the Box Onchain blocks for both contract and UI. Completed [here](https://github.com/coinbase/build-onchain-apps/pull/207)
- [x] Explain in the README how to build an ABI for a contract. Completed [here](https://github.com/coinbase/build-onchain-apps/pull/207)
- [x] Explain how to deploy a new contract that is not pre-made. Completed [here](https://github.com/coinbase/build-onchain-apps/pull/207)

**Other ideas**
- [x]  Would be cool to have https://www.npmjs.com/package/stylelint-order working, so the CSS is a bit easier to read. https://github.com/coinbase/build-onchain-apps/pull/159
- [x] Would love to see how we can use similar style and energy of Vitepress without using Vitepress. I might going to create a small library that recreates Vitepress for React, just the basic functionality.
- [ ] ~~~

**Comment by Sneh1999** [comment]
Solidity enhancements should be completed now! Let me know if you can think of any other
