### ISSUE TITLE
Bug: “Buy me coffee” button does not work when out of gas

### ISSUE THREAD

**Issue by leo5imon** [coinbase/build-onchain-apps#256]
### Describe the bug and the steps to reproduce it

The "Send 1 Coffee for 0.001ETH" don't return anything while out-of-gas.

### What's the expected behavior?

Could be great to add an alert or visual notification when trying to use it.
Other buttons open Metamask pop-up, but this one don't.

**Comment by Zizzamia** [comment]
Great catch! Thank you @leo5imon 
That's for sure a missing experience that we need to cover.

@leo5imon if you catch more of those, please let them coming, those notes are pure gold ✨

**Comment by arsood** [comment]
@leo5imon thanks for reporting! This merged PR should fix this issue: https://github.com/coinbase/build-onchain-apps/pull/311
