### ISSUE TITLE
Bug: metadata.metadataBase is not set for resolving social open graph or twitter images

### ISSUE THREAD

**Issue by leo5imon** [coinbase/build-onchain-apps#257]
### Describe the bug and the steps to reproduce it

Warning during development : metadata.metadataBase is not set for resolving social open graph or twitter images, using "http://localhost:3000". See https://nextjs.org/docs/app/api-reference/functions/generate-metadata#metadatabase

### What's the expected behavior?

Can be great to remove it, pretty painful to get this error at every build

**Comment by Zizzamia** [comment]
Oh yeah, I have been noticing that too.
I am going to get our F1 mechanic on top of this.

**Comment by Zizzamia** [comment]
@leo5imon fix this one by @wespickett
