### ISSUE TITLE
Bug Bash Jan 2024

### ISSUE THREAD

**Issue by Zizzamia** [coinbase/build-onchain-apps#259]
Time to catch some bugs and ideas for BOAT

![everart image (1)](https://github.com/coinbase/build-onchain-apps/assets/829214/21fae774-aad8-4667-ba7e-b5a2e3bb1290)

**Comment by robpolak** [comment]
### Describe the bug and the steps to reproduce it

Multiple Examples break if you don't have enough funds.   Fails for Coffee and SignatureMint flows.

### What's the expected behavior?

The UX should either show you a warning or toast that you do not have enough funds

![image](https://github.com/coinbase/build-onchain-apps/assets/7040142/b8689790-3a62-4f70-bd49-c4687897f4a8)

**Comment by renanmav** [comment]
Onchain avatar still doesn't work for me. I have my avatar field setup in ENS.

![onchain-avatar-does-not-work](https://github.com/coinbase/build-onchain-apps/assets/43140758/f5a72166-c8c0-4ac5-8773-e8dde55cdf7f)

![ens-avatar](https://github.com/coinbase/build-onchain-apps/assets/43140758/c08c5c28-5e47-438f-aa6a-947cc94f2950)

**Comment by cnasc** [comment]
We should add the instruction to get a WalletConnect ID here: https://github.com/coinbase/build-onchain-apps/blob/main/src/utils/apps.ts#L55 
This info is in the README, but the instructions presented by the generator give the impression that the app is ready to go right away.

Bonus points: be able to pass the ID to the generator and have it create `.env.local` with this variable prefilled

**Comment by renanmav** [comment]
Header should not be on top of get started https://build-onchain-apps.vercel.app/#get-started.

It should contain some spacing.

![get-started-header](https://github.com/coinbase/build-onchain-apps/assets/43140758/339c016b-b8cf-477d-a095-88745ebf54fc)

**Comment by Sneh1999** [comment]
Note here is not coming as a comment:
![image](https://github.com/coinbase/build-onchain-apps/assets/35871990/92e7c297-df49-41f8-90f0-8c04e05a1a14)

**Comment by robpolak** [comment]
### Describe the bug and the steps to reproduce it

On the buy me a coffee screen we should bound the inputs to a given length to ensure a user won't have high gas fees.

### What's the expected behavior?

The UX should limit the number of characters and we should explain to users how variable storage works on solidity contracts.  

![image](https://github.com/coinbase/build-onchain-apps/assets/7040142/d8240207-2d4f-4ec3-91b5-49956b626dfb)

**Comment by Sneh1999** [comment]
Not enough padding on my monitor between Guide and the messages
![image](https://github.com/coinbase/build-onchain-apps/assets/35871990/b48c7a6b-ceed-45e1-8c34-bf4c56b66c0b)

**Comment by cnasc** [comment]
<img width="997" alt="image" src="https://github.com/coinbase/build-onchain-apps/assets/9300702/25305135-3441-4c94-a3e0-5acfcf03907f">

It mildly bothers me that the footer is so tall

**Comment by Sneh1999** [comment]
No confirmation and loading screen when we click on `Send 1 Coffee for 0.001 ETH`
![image](https://github.com/coinbase/build-onchain-apps/assets/35871990/104aa842-64d7-47bd-b2c7-b425af55c692)

**Comment by robpolak** [comment]
We should not surface free-form data from the blockchain.. At a minimum, put some limits on the amount of characters we show.  (e.g. show 20 characters and then a modal + text area for the rest)

![image](https://github.com/coinbase/build-onchain-apps/assets/7040142/74a464c3-137a-41aa-9ce6-2240b2fadc63)

**Comment by renanmav** [comment]
Buy me a coffee experience says I don't have enough ETH. I have 2 ETH on Base Sepolia.

![buy-me-coffee-not-enough-eth](https://github.com/coinbase/build-onchain-apps/assets/43140758/2a8c09d5-620d-4ae1-bc20-3bf5e8cb67dd)
![eth-sepolia-balance](https://github.com/coinbase/build-onchain-apps/assets/43140758/99546bc4-d6ca-4411-8b74-d30b315b07c8)

**Comment by cnasc** [comment]
<img width="880" alt="image" src="https://github.com/coinbase/build-onchain-apps/assets/9300702/9020a142-2ff3-48a2-b31b-3f739f4fc3a3">

Horizontal scrolling is not my favorite (even less so when my screen is already wide enough to show the whole line). We may be able to clamp these lines to 72/80 chars (can use backslash to break up the non-comment line)

**Comment by joelmcgill** [comment]
Nit: Probably should include  the instruction to CD into the  created app or into `/apps` directory before running `yarn dev` on step 3 
<img width="382" alt="image" src="https://github.com/coinbase/build-onchain-apps/assets/80292937/76dfa0b7-8830-48c8-b280-e24cd9f9e04e">

**Comment by joelmcgill** [comment]
Additional spacing on the warning here and perhaps make it red 
<img width="328" alt="image" src="https://github.com/coinbase/build-onchain-apps/assets/80292937/a2ddd63e-9643-4f9e-a160-15cdbdcd1a65">

**Comment by Zizzamia** [comment]
Most of them are solved, so we can call it the day and do one more soon.
