### ISSUE TITLE
Bug: NextJs dynamic routing not working

### ISSUE THREAD

**Issue by michaelcohen716** [coinbase/build-onchain-apps#273]
### Describe the bug and the steps to reproduce it

the `app/` folder in the repo drives the routing. nextjs documentation says that adding a file `[slug].tsx` with the brackets in the folder will add a dynamic route -- the equivalent of having a `token/:address` route in other kinds of routers. I currently have a basic page at file `token/[slug].tsx`

```
import { useRouter } from 'next/router'
 
export default function Page() {
  const router = useRouter()
  console.log('router', router);
  return (<p>{router.query.slug}</p>);
}


```
<img width="234" alt="Screenshot 2024-01-24 at 4 30 11 PM" src="https://github.com/coinbase/build-onchain-apps/assets/30220134/bcffea80-59b5-446c-abf5-3a05343cf7e9">

but when i go to the route `/token/123`, i get a 404, suggesting the routing isn't working. for reference, the route `/token` is displaying properly, via the `index.tsx` file in my token/ folder

### What's the expected behavior?

the app is expected to route to `token/123` with 123 being passed as a prop to the component

### What version of the libraries are you using?

I'm not sure exactly where to find the BOAT version, but I cloned the repo about one week ago.

next 13.5.6
react ^18

**Comment by wespickett** [comment]
@michaelcohen716 not a bug, you just need to put the [slug] part as a subfolder vs file. See example: https://github.com/coinbase/build-onchain-apps/compare/wes/slug-example

**Comment by michaelcohen716** [comment]
works, thank you
