### ISSUE TITLE
Feature Request: Component folder organization

### ISSUE THREAD

**Issue by n3ps** [coinbase/build-onchain-apps#274]
### Describe the solution you'd like

I see you've adopted the [app router suggestion](https://github.com/coinbase/build-onchain-apps/issues/91), nice. 

Re: UI components, why not move them into the `app` folder as well? Instead of keeping them in somewhat disjointed `src\components`, `src\pageComponents` folders? (aren't most of the files in a project source code anyway?)

Something like this (from Next.js docs):

<img width="241" alt="image" src="https://github.com/coinbase/build-onchain-apps/assets/1104590/40ebf7c2-ade8-40af-9ce0-a63ee941d52d">

**Comment by Zizzamia** [comment]
> why not move them into the app folder as well?

Probably I am a Next.js App noob, but isn't the App folder just for routing?

Also, I like my routing and my components split in different folders, [I am not an animal after all](https://www.youtube.com/watch?v=5d5albVARGA&t=81s). 😆

If I start mixing routing with components, than it gets very quickly a bad practice where folks stop thinking on what to re-use and they just start creating a bunch of spaghetti code.

Small contranints in my opinion help enforce more clean code.

**Comment by arsood** [comment]
@n3ps what do we think? Any resolution here or should we close this issue?

**Comment by Zizzamia** [comment]
Going to close this for now. I like my routes split from my components. Although some folks might disagree, in that case they can create a new project and still mix and match as they prefer.
