### ISSUE TITLE
Feature Request: Typescript import path

### ISSUE THREAD

**Issue by kyhyco** [coinbase/build-onchain-apps#359]
### Describe the solution you'd like

Currently, frontend code doesn't use alias import path. For example,

```typescript
import import Banner from '../../src/components/banner/banner';
```

Should we consider an alias to make the path more readable? Some examples:
```typescript
import import Banner from '@template/components/banner/banner';

import import Banner from '@/components/banner/banner';
```

This will require modifying `template/.tsconfig.json` with the following `compilerOptions`
```json
{
  "compilerOptions": {
    "paths": {
      "@template": [
        "src/*"
      ]
    }
  }
}
```

### Describe alternatives you've considered.

If we want to be very fancy, we could ask the user to set the alias like how `create-next-app` does.

**Comment by Yuripetusko** [comment]
I agree, this makes imports more clear and easier to read. The common pattern I like is alias by domain e.g.

```
"components/*": [
    "src/components/*"
  ],
  "utils/*": [
    "src/utils/*"
  ],
  "hooks/*": [
    "src/hooks/*"
  ],
```

**Comment by Zizzamia** [comment]
I like this one, but not sure if it's a big no no for some other reason
```ts
import import Banner from '@/components/banner/banner';
```

**Comment by Yuripetusko** [comment]
> I like this one, but not sure if it's a big no no for some other reason
> 
> ```ts
> import import Banner from '@/components/banner/banner';
> ```

I think it's fine as long as it's clear that it's internal alias and not external package. I  do see this @/ pattern lately quite often, so I guess I'm not alone that is getting used to @/ meaning local path alias

**Comment by Zizzamia** [comment]
Ok last idea, how about `@boat/~~~`, if we like that, than let's do it.

Ideally folks can change `@boat` with anything they want if they want to customize it.

**Comment by Yuripetusko** [comment]
> Ok last idea, how about `@boat/~~~`, if we like that, than let's do it.
> 
> Ideally folks can change `@boat` with anything they want if they want to customize it.

Depends on what are the plans with this repo. If you are planning to turn it into something like create react app, or a starter/boilerplate project, which can be installed through a cli which prompts user which template he want to use, then it's better to use something generic like `@`, but if this is "examples" repo, then using something fun/branded like `@boat` is cool. I think making it less serious and adding a branded elements like a `@boat` acronym is good direction in general

**Comment by Zizzamia** [comment]
That was my thinking as well. That's why I think leaning towards `@/` might be best.
