### ISSUE TITLE
Feature Request: Template Folder Restructure

### ISSUE THREAD

**Issue by spennyp** [coinbase/build-onchain-apps#363]
### Describe the solution you'd like

IMO, contracts should not live within the Nextjs project.

The foundry project has a completely different build environment, deployment process, and potentially different team working on it.

A folder structure like this seems to make more sense:
```
.
├── README.md
├── .gitmodules
├── contracts
│   ├── foundry.toml
│   ├── lib
│   ├── src
│   ├── test
│   └── ...
└── web
    ├── package.json
    ├── public
    ├── src
    ├── tsconfig.json
    ├── yarn.lock
    └── ...

```

For example, like this project: https://github.com/papercliplabs/frames

**Comment by Zizzamia** [comment]
YES!!!! 100% right

@Sneh1999 can you take this one?

**Comment by Sneh1999** [comment]
Closing this request as this feature has been implemented!
