### ISSUE TITLE
Feature Request: Make onchainkit a dependency

### ISSUE THREAD

**Issue by spennyp** [coinbase/build-onchain-apps#364]
### Describe the solution you'd like

Currently, [onchainkit](https://github.com/coinbase/onchainkit) is not imported as a dependency, and a copy of the folder lives in the template.

Ideally, this is a dependency so we can pickup the latest and greatest from onchainkit without copy pasta.

**Comment by Zizzamia** [comment]
I think it is
https://github.com/coinbase/build-onchain-apps/blob/main/template/package.json#L21

and in the latest few PRs we started killing the old OnchainKit folder.

I guess that's something we did on Sunday, not sure if you used BOAT from before than.

**Comment by spennyp** [comment]
Ah awesome! My fault, I didn’t see this change!
