### ISSUE TITLE
Bug: Setup error - incorrect file renaming

### ISSUE THREAD

**Issue by matejos** [coinbase/build-onchain-apps#479]
### Describe the bug and the steps to reproduce it

When creating app with `npx @coinbase/build-onchain-apps@latest create`, the process will contain an error: `Error while renaming directories: Error: ENOENT: no such file or directory, rename '/home/.../web/src/OnchainProvidersWithRK.ts' -> '/home/.../web/src/onchainProviders.ts'`
This is because the existing file is `.tsx`, not `.ts`. Furthermore, capitalization is also incorrect (should be `OnchainProviders`, not `onchainProviders`).

### What's the expected behavior?

No errors

### What version of the libraries are you using?

latest

**Comment by Zizzamia** [comment]
This fix was merged and released with https://github.com/coinbase/build-onchain-apps/releases/tag/v0.28.1, please let me know if it's all good.

**Comment by matejos** [comment]
Yep it works!
