### ISSUE TITLE
Documentation Request: Remove walletconnect from rainbowkit options

### ISSUE THREAD

**Issue by michaelcohen716** [coinbase/build-onchain-apps#494]
### Is your documentation request related to a problem? Please describe.

Is there a way to change some config to do this? I don't see walletconnect in the wagmiConfig in the repo, but it is presented as one of the options to users connecting their wallets on mobile

users testing my app are reporting no issues connecting via rabby or metamask, but are unable to connect via walletconnect? my wallet connect id is properly included in wagmiConfig

**Comment by Zizzamia** [comment]
In the latest version of BOAT Wallet Connect was fully removed :)

**Comment by michaelcohen716** [comment]
is there some kind of docs or suggestions for migrating? would be helpful as i don't think i would like to start from scratch on my current repo

**Comment by michaelcohen716** [comment]
is it as simple as adopting the new OnchainProvider file and the files that tap into it?

**Comment by Zizzamia** [comment]
I don't think is best for you to migrate to the latest master, especially as the latest one has Smart Wallet which is only in Base Sepolia at the moment.

But I think is best for you to do a migration in a few weeks when Smart Wallet will be fully out.
