### ISSUE TITLE
Offline caching support 

### ISSUE THREAD

**Issue by alvaroraminelli-cb** [coinbase/build-onchain-apps#9]
### Is your feature request related to a problem? Please describe.

The app may experience longer loading times, which does not provide the same user experience as native apps.

### Describe the solution you'd like

Every time a page is visited it is cached locally on their device, and it will still be accessible offline. Pages once cached are served even if the user is offline.

**Comment by Zizzamia** [comment]
closing this one, as it's not a top of mind anymore.
